# -*- coding: utf-8 -*-
"""NLU assignment 2.2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11G7mThPMxDXKcdoSu3XLRdwJaMY47e9P
"""

import numpy as np
import matplotlib.pyplot as plt

import random
import string

"""**Vanilla RNN Model**"""

import numpy as np
class Vanilla_RNN: # vanilla rnn model
    def __init__(self, vocab_size, hidden_size=120, lr=0.02):

        # storing some config values
        self.vocab_size = vocab_size
        self.hidden_dim = hidden_size
        self.learning_rate = lr

        # shortcuts because typing full names repeatedly gets annoying
        V = self.vocab_size
        H = self.hidden_dim

        # --- Weight initialization ---
        # small random values are usually safe to start with
        # learned this the hard way after exploding gradients once
        self.w_x_h = np.random.randn(H, V) * 0.01
        self.w_h_h = np.random.randn(H, H) * 0.01
        self.w_h_y = np.random.randn(V, H) * 0.01

        # --- Bias terms ---
        # biases are just zeros for now
        self.b_h = np.zeros((H, 1))
        self.b_y = np.zeros((V, 1))

        # --- Adagrad memory variables ---
        # keeps track of squared gradients
        self.mem_wxh = np.zeros_like(self.w_x_h)
        self.mem_whh = np.zeros_like(self.w_h_h)
        self.mem_why = np.zeros_like(self.w_h_y)

        self.mem_bh = np.zeros_like(self.b_h)
        self.mem_by = np.zeros_like(self.b_y)

        # might refactor optimizer later if this grows bigger


# forward step (used for prediction/inference)
    def forward(self, char_index, prev_h):

        # convert char index to one-hot vector
        x = np.zeros((self.vocab_size, 1))
        x[char_index] = 1

        # compute next hidden state
        h = np.tanh(
            np.dot(self.w_x_h, x) +
            np.dot(self.w_h_h, prev_h) +
            self.b_h
        )

        # output layer
        y = np.dot(self.w_h_y, h) + self.b_y

        # softmax (not the most numerically stable version but fine for now)
        probs = np.exp(y) / np.sum(np.exp(y))

        return probs, h


# training step (forward + backward + update)
    def train_step(self, inputs, prev_h, targets):

        # dictionaries to store values across time
        xs = {}
        hs = {}
        ys = {}
        ps = {}

        hs[-1] = np.copy(prev_h)   # storing initial hidden state

        total_loss = 0

        # -------- FORWARD PASS --------
        for t in range(len(inputs)):

            xs[t] = np.zeros((self.vocab_size, 1))
            xs[t][inputs[t]] = 1

            hs[t] = np.tanh(
                np.dot(self.w_x_h, xs[t]) +
                np.dot(self.w_h_h, hs[t-1]) +
                self.b_h
            )

            ys[t] = np.dot(self.w_h_y, hs[t]) + self.b_y

            # again using simple softmax
            ps[t] = np.exp(ys[t]) / np.sum(np.exp(ys[t]))

            # negative log likelihood loss
            target_idx = targets[t]
            total_loss += -np.log(ps[t][target_idx, 0])


        # -------- BACKWARD PASS --------

        d_wxh = np.zeros_like(self.w_x_h)
        d_whh = np.zeros_like(self.w_h_h)
        d_why = np.zeros_like(self.w_h_y)

        d_bh = np.zeros_like(self.b_h)
        d_by = np.zeros_like(self.b_y)

        dh_next = np.zeros_like(prev_h)  # gradient flowing backward through time


        for t in reversed(range(len(inputs))):

            dy = np.copy(ps[t])
            dy[targets[t]] -= 1   # derivative of cross entropy

            # output layer gradients
            d_why += np.dot(dy, hs[t].T)
            d_by += dy

            # backprop into hidden state
            dh = np.dot(self.w_h_y.T, dy) + dh_next

            # derivative through tanh
            dh_raw = (1 - hs[t] * hs[t]) * dh

            d_bh += dh_raw
            d_wxh += np.dot(dh_raw, xs[t].T)
            d_whh += np.dot(dh_raw, hs[t-1].T)

            dh_next = np.dot(self.w_h_h.T, dh_raw)


        # -------- Gradient Clipping --------
        # helps prevent exploding gradients
        for grad in [d_wxh, d_whh, d_why, d_bh, d_by]:
            np.clip(grad, -5, 5, out=grad)


        # -------- Adagrad Update --------
        params = [self.w_x_h, self.w_h_h, self.w_h_y, self.b_h, self.b_y]
        grads  = [d_wxh, d_whh, d_why, d_bh, d_by]
        mems   = [self.mem_wxh, self.mem_whh, self.mem_why, self.mem_bh, self.mem_by]

        for p, g, m in zip(params, grads, mems):

            # accumulate squared gradients
            m += g * g

            # parameter update
            p += -self.learning_rate * g / (np.sqrt(m) + 1e-8)


        # returning final loss and last hidden state
        last_h = hs[len(inputs)-1]

        return total_loss, last_h





"""**Bidirectional LSTM**"""

import numpy as np

class BiLSTM:
    def __init__(self, vocab_size, hidden_size=128, learning_rate=0.02):

        self.vocab_size = vocab_size
        self.hidden_dim = hidden_size
        self.lr = learning_rate

        H = hidden_size
        V = vocab_size

        # size after concatenating hidden state and input
        concat_size = H + V

        # ----- Forward LSTM weights -----
        # Using stacked gate weights [forget | input | candidate | output]
        self.W_forward = np.random.randn(4 * H, concat_size) * 0.01
        self.b_forward = np.zeros((4 * H, 1))

        # ----- Backward LSTM weights -----
        self.W_backward = np.random.randn(4 * H, concat_size) * 0.01
        self.b_backward = np.zeros((4 * H, 1))

        # ----- Output layer -----
        # Takes both forward and backward hidden states
        self.W_out = np.random.randn(V, 2 * H) * 0.01
        self.b_out = np.zeros((V, 1))



    # sigmoid helper
    def sigmoid(self, x):
        return 1.0 / (1.0 + np.exp(-x))


    # softmax helper
    def softmax(self, x, axis=-1):

        # subtracting max for numerical stability
        shifted = x - np.max(x, axis=axis, keepdims=True)
        e = np.exp(shifted)

        return e / np.sum(e, axis=axis, keepdims=True)


    # ------------------------------------------------
    # Single LSTM step (used by both forward/backward)
    # ------------------------------------------------
    def lstm_forward_step(self, x, h_prev, c_prev, W, b):

        # concatenate previous hidden state and input
        z = np.vstack((h_prev, x))

        gates = np.dot(W, z) + b

        H = self.hidden_dim

        # split gates
        f = self.sigmoid(gates[0:H])
        i = self.sigmoid(gates[H:2*H])
        c_tilde = np.tanh(gates[2*H:3*H])
        o = self.sigmoid(gates[3*H:4*H])

        # cell update
        c = f * c_prev + i * c_tilde
        h = o * np.tanh(c)

        # caching values for backprop
        cache = (z, f, i, c_tilde, o, c, c_prev)

        return h, c, cache


    # ------------------------------------------------
    # Backprop for one LSTM step
    # ------------------------------------------------
    def lstm_backward_step(self, dh_next, dc_next, cache, W):

        z, f, i, c_bar, o, c, c_prev = cache
        H = self.hidden_dim

        # gradient through cell
        dc = dc_next + dh_next * o * (1 - np.tanh(c) ** 2)

        # gate gradients
        do = dh_next * np.tanh(c) * o * (1 - o)
        dc_bar = dc * i * (1 - c_bar ** 2)
        di = dc * c_bar * i * (1 - i)
        df = dc * c_prev * f * (1 - f)

        # stack them again
        dgates = np.vstack((df, di, dc_bar, do))

        # parameter gradients
        dW = np.dot(dgates, z.T)
        db = dgates

        dz = np.dot(W.T, dgates)

        dh_prev = dz[:H]
        dx = dz[H:]
        dc_prev = dc * f

        return dx, dh_prev, dc_prev, dW, db


    # ------------------------------------------------
    # One training step (forward + backward + update)
    # ------------------------------------------------
    def train_step(self, inputs, targets, h_f_prev, c_f_prev, h_b_next, c_b_next):

        T = len(inputs)
        H = self.hidden_dim

        # storing states
        h_f, c_f, cache_f = {}, {}, {}
        h_b, c_b, cache_b = {}, {}, {}

        y_cache = {}
        prob_cache = {}

        h_f[-1], c_f[-1] = np.copy(h_f_prev), np.copy(c_f_prev)
        h_b[T], c_b[T] = np.copy(h_b_next), np.copy(c_b_next)

        total_loss = 0


        # -------- Forward LSTM pass --------
        for t in range(T):

            x = np.zeros((self.vocab_size, 1))
            x[inputs[t]] = 1

            h_f[t], c_f[t], cache_f[t] = self.lstm_forward_step(
                x, h_f[t-1], c_f[t-1], self.W_forward, self.b_forward
            )


        # -------- Backward LSTM pass --------
        for t in reversed(range(T)):

            x = np.zeros((self.vocab_size, 1))
            x[inputs[t]] = 1

            h_b[t], c_b[t], cache_b[t] = self.lstm_forward_step(
                x, h_b[t+1], c_b[t+1], self.W_backward, self.b_backward
            )


        # -------- Output prediction --------
        for t in range(T):

            combined = np.vstack((h_f[t], h_b[t]))

            y = np.dot(self.W_out, combined) + self.b_out
            p = self.softmax(y, axis=0)

            y_cache[t] = y
            prob_cache[t] = p

            total_loss += -np.log(p[targets[t], 0] + 1e-8)


        # ======================================
        # Backpropagation
        # ======================================

        dW_f, db_f = np.zeros_like(self.W_forward), np.zeros_like(self.b_forward)
        dW_b, db_b = np.zeros_like(self.W_backward), np.zeros_like(self.b_backward)
        dW_y, db_y = np.zeros_like(self.W_out), np.zeros_like(self.b_out)

        dh_f_store = {}
        dh_b_store = {}


        # output gradients
        for t in range(T):

            dy = np.copy(prob_cache[t])
            dy[targets[t]] -= 1

            combined = np.vstack((h_f[t], h_b[t]))

            dW_y += np.dot(dy, combined.T)
            db_y += dy

            dh_combined = np.dot(self.W_out.T, dy)

            dh_f_store[t] = dh_combined[:H]
            dh_b_store[t] = dh_combined[H:]


        # -------- Forward LSTM BPTT --------
        dh_next = np.zeros_like(h_f[-1])
        dc_next = np.zeros_like(c_f[-1])

        for t in reversed(range(T)):

            dh = dh_f_store[t] + dh_next

            _, dh_next, dc_next, dW, db = self.lstm_backward_step(
                dh, dc_next, cache_f[t], self.W_forward
            )

            dW_f += dW
            db_f += db


        # -------- Backward LSTM BPTT --------
        dh_next = np.zeros_like(h_b[T])
        dc_next = np.zeros_like(c_b[T])

        for t in range(T):

            dh = dh_b_store[t] + dh_next

            _, dh_next, dc_next, dW, db = self.lstm_backward_step(
                dh, dc_next, cache_b[t], self.W_backward
            )

            dW_b += dW
            db_b += db


        # -------- Gradient clipping --------
        for grad in [dW_f, db_f, dW_b, db_b, dW_y, db_y]:
            np.clip(grad, -5, 5, out=grad)


        # -------- SGD update --------
        self.W_forward -= self.lr * dW_f
        self.b_forward -= self.lr * db_f

        self.W_backward -= self.lr * dW_b
        self.b_backward -= self.lr * db_b

        self.W_out -= self.lr * dW_y
        self.b_out -= self.lr * db_y


        # return loss + final states
        return total_loss, h_f[T-1], c_f[T-1], h_b[0], c_b[0]


    # ------------------------------------------------
    # Prediction for a sequence
    # ------------------------------------------------
    def predict_sequence(self, input_sequence, idx_to_char):

        T = len(input_sequence)
        H = self.hidden_dim

        h_f, c_f = {-1: np.zeros((H, 1))}, {-1: np.zeros((H, 1))}
        h_b, c_b = {T: np.zeros((H, 1))}, {T: np.zeros((H, 1))}

        # forward pass
        for t in range(T):

            x = np.zeros((self.vocab_size, 1))
            x[input_sequence[t]] = 1

            h_f[t], c_f[t], _ = self.lstm_forward_step(
                x, h_f[t-1], c_f[t-1], self.W_forward, self.b_forward
            )


        # backward pass
        for t in reversed(range(T)):

            x = np.zeros((self.vocab_size, 1))
            x[input_sequence[t]] = 1

            h_b[t], c_b[t], _ = self.lstm_forward_step(
                x, h_b[t+1], c_b[t+1], self.W_backward, self.b_backward
            )


        predictions = []

        for t in range(T):

            combined = np.vstack((h_f[t], h_b[t]))

            y = np.dot(self.W_out, combined) + self.b_out
            p = self.softmax(y, axis=0)

            pred_idx = np.argmax(p)

            predictions.append(idx_to_char[pred_idx])

        return predictions





"""**RNN with Basic Attention**"""

import numpy as np

class RNN_Attention:
    def __init__(self, vocab_size, hidden_size=128, learning_rate=0.002):

        self.vocab_size = vocab_size
        self.hidden_dim = hidden_size
        self.lr = learning_rate

        H = hidden_size
        V = vocab_size

        # ---------------- Encoder weights ----------------
        self.W_in_enc = np.random.randn(H, V) * 0.01
        self.W_h_enc = np.random.randn(H, H) * 0.01
        self.b_enc = np.zeros((H, 1))

        # ---------------- Decoder weights ----------------
        self.W_in_dec = np.random.randn(H, V) * 0.01
        self.W_h_dec = np.random.randn(H, H) * 0.01
        self.W_ctx = np.random.randn(H, H) * 0.01
        self.b_dec = np.zeros((H, 1))

        # ---------------- Output layer ----------------
        self.W_out = np.random.randn(V, H) * 0.01
        self.b_out = np.zeros((V, 1))

        # ---------------- Adagrad memory ----------------
        # honestly not always necessary for tiny experiments
        self.mem_W_in_enc = np.zeros_like(self.W_in_enc)
        self.mem_W_h_enc = np.zeros_like(self.W_h_enc)
        self.mem_b_enc = np.zeros_like(self.b_enc)

        self.mem_W_in_dec = np.zeros_like(self.W_in_dec)
        self.mem_W_h_dec = np.zeros_like(self.W_h_dec)
        self.mem_W_ctx = np.zeros_like(self.W_ctx)
        self.mem_b_dec = np.zeros_like(self.b_dec)

        self.mem_W_out = np.zeros_like(self.W_out)
        self.mem_b_out = np.zeros_like(self.b_out)


    # ---------------- Softmax ----------------
    def softmax(self, x, axis=-1):

        # subtract max for stability (learned this after getting NaNs once)
        shifted = x - np.max(x, axis=axis, keepdims=True)

        e = np.exp(shifted)
        return e / np.sum(e, axis=axis, keepdims=True)


    # ---------------- Encoder ----------------
    def encoder(self, seq, h_prev):

        enc_states = {}
        enc_states[-1] = np.copy(h_prev)

        xs = {}

        for t in range(len(seq)):

            x = np.zeros((self.vocab_size, 1))
            x[seq[t]] = 1
            xs[t] = x

            enc_states[t] = np.tanh(
                np.dot(self.W_in_enc, x) +
                np.dot(self.W_h_enc, enc_states[t-1]) +
                self.b_enc
            )

        return enc_states, xs


    # ---------------- Attention ----------------
    def attention(self, decoder_h, H_enc):

        # basic dot-product attention
        # H_enc shape = (Hidden, SequenceLength)

        scores = np.dot(decoder_h.T, H_enc)  # (1, N)

        weights = self.softmax(scores, axis=1)

        context = np.dot(H_enc, weights.T)  # (Hidden, 1)

        return context, weights


    # ------------------------------------------------
    # Training step (encoder + decoder + attention)
    # ------------------------------------------------
    def train_step(self, inputs, h_enc_prev, h_dec_prev, targets):

        T = len(inputs)

        # ----- Encoder forward pass -----
        enc_states, xs_enc = self.encoder(inputs, h_enc_prev)

        # stacking encoder states for easier attention computation
        H_enc = np.hstack([enc_states[t] for t in range(T)])

        xs_dec, hs_dec = {}, {}
        contexts, attn_weights = {}, {}

        y_cache, prob_cache = {}, {}

        hs_dec[-1] = np.copy(h_dec_prev)

        total_loss = 0


        # ----- Decoder forward -----
        for t in range(T):

            x = np.zeros((self.vocab_size, 1))
            x[inputs[t]] = 1
            xs_dec[t] = x

            ctx, w = self.attention(hs_dec[t-1], H_enc)

            contexts[t] = ctx
            attn_weights[t] = w

            hs_dec[t] = np.tanh(
                np.dot(self.W_in_dec, x) +
                np.dot(self.W_h_dec, hs_dec[t-1]) +
                np.dot(self.W_ctx, ctx) +
                self.b_dec
            )

            y = np.dot(self.W_out, hs_dec[t]) + self.b_out
            p = self.softmax(y, axis=0)

            y_cache[t] = y
            prob_cache[t] = p

            total_loss += -np.log(p[targets[t], 0] + 1e-8)


        # ------------------------------------------------
        # Backpropagation
        # ------------------------------------------------

        dW_in_enc = np.zeros_like(self.W_in_enc)
        dW_h_enc = np.zeros_like(self.W_h_enc)
        db_enc = np.zeros_like(self.b_enc)

        dW_in_dec = np.zeros_like(self.W_in_dec)
        dW_h_dec = np.zeros_like(self.W_h_dec)
        dW_ctx = np.zeros_like(self.W_ctx)
        db_dec = np.zeros_like(self.b_dec)

        dW_out = np.zeros_like(self.W_out)
        db_out = np.zeros_like(self.b_out)

        dh_next_rnn = np.zeros_like(h_dec_prev)
        dh_next_attn = np.zeros_like(h_dec_prev)

        dH_enc_total = np.zeros_like(H_enc)


        # ----- Decoder BPTT -----
        for t in reversed(range(T)):

            dy = np.copy(prob_cache[t])
            dy[targets[t]] -= 1

            dW_out += np.dot(dy, hs_dec[t].T)
            db_out += dy

            dh = (
                np.dot(self.W_out.T, dy)
                + dh_next_rnn
                + dh_next_attn
            )

            dh_raw = (1 - hs_dec[t] * hs_dec[t]) * dh

            db_dec += dh_raw
            dW_in_dec += np.dot(dh_raw, xs_dec[t].T)
            dW_h_dec += np.dot(dh_raw, hs_dec[t-1].T)
            dW_ctx += np.dot(dh_raw, contexts[t].T)

            # gradient into context vector
            d_context = np.dot(self.W_ctx.T, dh_raw)

            w = attn_weights[t]

            d_weights = np.dot(H_enc.T, d_context).T

            dH_enc_total += np.dot(d_context, w)

            # softmax derivative
            d_scores = w * (d_weights - np.sum(d_weights * w, axis=1, keepdims=True))

            dh_next_attn = np.dot(H_enc, d_scores.T)

            dH_enc_total += np.dot(hs_dec[t-1], d_scores)

            dh_next_rnn = np.dot(self.W_h_dec.T, dh_raw)


        # ----- Encoder BPTT -----
        dh_enc_next = np.zeros_like(h_enc_prev)

        for t in reversed(range(T)):

            dh_enc = dh_enc_next + dH_enc_total[:, t].reshape(-1, 1)

            dh_raw = (1 - enc_states[t] * enc_states[t]) * dh_enc

            db_enc += dh_raw
            dW_in_enc += np.dot(dh_raw, xs_enc[t].T)
            dW_h_enc += np.dot(dh_raw, enc_states[t-1].T)

            dh_enc_next = np.dot(self.W_h_enc.T, dh_raw)


        # ------------------------------------------------
        # Weight updates
        # ------------------------------------------------

        params = [
            self.W_in_enc, self.W_h_enc, self.b_enc,
            self.W_in_dec, self.W_h_dec, self.W_ctx, self.b_dec,
            self.W_out, self.b_out
        ]

        grads = [
            dW_in_enc, dW_h_enc, db_enc,
            dW_in_dec, dW_h_dec, dW_ctx, db_dec,
            dW_out, db_out
        ]

        # gradient clipping (very helpful for RNNs)
        for g in grads:
            np.clip(g, -5, 5, out=g)

        # simple SGD update
        for p, g in zip(params, grads):
            p -= self.lr * g


        return total_loss, enc_states[T-1], hs_dec[T-1]


    # ------------------------------------------------
    # Inference / generation
    # ------------------------------------------------
    def forward(self, encoder_input, start_idx, h_enc_prev, h_dec_prev, idx_to_char, length=10):

        enc_states, _ = self.encoder(encoder_input, h_enc_prev)

        T = len(encoder_input)

        H_enc = np.hstack([enc_states[t] for t in range(T)])

        dec_h = np.copy(h_dec_prev)

        current_char = start_idx

        generated = idx_to_char[start_idx]


        for _ in range(length):

            x = np.zeros((self.vocab_size, 1))
            x[current_char] = 1

            ctx, _ = self.attention(dec_h, H_enc)

            dec_h = np.tanh(
                np.dot(self.W_in_dec, x) +
                np.dot(self.W_h_dec, dec_h) +
                np.dot(self.W_ctx, ctx) +
                self.b_dec
            )

            y = np.dot(self.W_out, dec_h) + self.b_out
            p = self.softmax(y, axis=0)

            current_char = np.random.choice(self.vocab_size, p=p.ravel())

            generated += idx_to_char[current_char]

        return generated



"""**Model Training**"""

import numpy as np

def train_model(model, data, seq_len=10, epochs=50):
    losses = []

    # Determine hidden dimension dynamically
    H_dim = model.H if hasattr(model, 'H') else model.hidden_dim

    for epoch in range(epochs):
        total_loss = 0

        # Initialize Forward states ONCE per epoch (Stateful across contiguous chunks)
        h_prev = np.zeros((H_dim, 1))
        h_prev_f = np.zeros((H_dim, 1))
        c_prev_f = np.zeros((H_dim, 1))

        # Step by seq_len to ensure chunks are strictly contiguous!
        # We need seq_len + 1 characters total to get a sequence of inputs and a sequence of targets
        for i in range(0, len(data) - seq_len, seq_len):

            # Slice the contiguous chunk
            seq = data[i : i + seq_len + 1]
            inputs_seq = seq[:-1]
            targets_seq = seq[1:]

            # --- Vanilla RNN ---
            if type(model).__name__ == "Vanilla_RNN":
                current_loss, h_prev = model.train_step(inputs_seq, h_prev, targets_seq)
                total_loss += current_loss

            # --- Bidirectional LSTM ---
            elif type(model).__name__ == "BiLSTM":
                # MUST reset backward states for every chunk (we don't know the "future" state)
                h_b_next = np.zeros((H_dim, 1))
                c_b_next = np.zeros((H_dim, 1))

                # Note: Signature matches the corrected BLSTM we wrote earlier
                current_loss, h_prev_f, c_prev_f, _, _ = model.train_step(inputs_seq, targets_seq, h_prev_f, c_prev_f, h_b_next, c_b_next)
                total_loss += current_loss

            # --- RNN with Attention ---
            elif type(model).__name__ == "RNN_Attention":
                # Reset states per sequence. Seq2Seq models don't typically carry state across chunks
                h_enc_prev_attn = np.zeros((H_dim, 1))
                h_dec_prev_attn = np.zeros((H_dim, 1))

                current_loss, _, _ = model.train_step(inputs_seq, h_enc_prev_attn, h_dec_prev_attn, targets_seq)
                total_loss += current_loss

        losses.append(total_loss)
        print(f"Epoch: {epoch} | Loss: {total_loss:.4f}")

    return losses



with open("TrainingNames.txt") as f:
    names = [line.strip().lower() for line in f]

text = "\n".join(names)

chars = sorted(list(set(text)))
vocab_size = len(chars)

c_to_idx = {c:i for i,c in enumerate(chars)}
idx_to_char = {i:c for c,i in c_to_idx.items()}

# converting text to indices
data = [c_to_idx[c] for c in text]

rnn_model = Vanilla_RNN(vocab_size)
rnn_loss = train_model(rnn_model,data)

blstm_model = BiLSTM(vocab_size)
blstm_loss = train_model(blstm_model,data)

attn_model = RNN_Attention(vocab_size) # This will now use the corrected class definition
attn_loss = train_model(attn_model,data) # This will use the corrected train_s

plt.plot(rnn_loss,label="Vanilla RNN")
plt.plot(blstm_loss,label="BLSTM")
plt.plot(attn_loss,label="RNN+Attention")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.title("Model Comparison")
plt.show()

import numpy as np

def generate_name(model, start_char, c_to_idx, idx_to_char, vocab_size, length=12):
    """
    Generates a name character-by-character using the specified model.
    """
    start_idx = c_to_idx[start_char]
    name = start_char
    current_char_idx = start_idx

    # ==========================================
    # 1. Vanilla RNN Generation (Working!)
    # ==========================================
    if type(model).__name__ == 'Vanilla_RNN':
        h_prev = np.zeros((model.hidden_dim, 1))
        for _ in range(length - 1):
            probs, h_prev = model.forward(current_char_idx, h_prev)
            current_char_idx = np.random.choice(vocab_size, p=probs.ravel())
            name += idx_to_char[current_char_idx]

    # ==========================================
    # 2. BiLSTM Generation (The Dummy Sequence Hack)
    # ==========================================
    elif type(model).__name__ == 'BiLSTM':
        # 1. Create a dummy sequence of the target length.
        # We start with the start_idx, and fill the rest with random characters
        # so the backward pass has something to read.
        dummy_sequence = [start_idx] + [np.random.choice(vocab_size) for _ in range(length - 1)]

        # 2. Call the method EXACTLY as the traceback expects: (input_sequence, idx_to_char)
        output = model.predict_sequence(dummy_sequence, idx_to_char)

        # 3. Format the output
        if isinstance(output, list):
            name = "".join(output)
        elif isinstance(output, str):
            name = output
        else:
            name = str(output)

   # ==========================================
    # 3. RNN Attention Generation (FIXED)
    # ==========================================
    elif type(model).__name__ == 'RNN_Attention':
        initial_encoder_input = [start_idx]
        h_enc_init = np.zeros((model.hidden_dim, 1))
        h_dec_init = np.zeros((model.hidden_dim, 1))

        # Passing ALL arguments in the exact order the traceback expects
        generated_string = model.forward(
            initial_encoder_input,
            start_idx,
            h_enc_init,
            h_dec_init,
            idx_to_char,  # <-- Added the missing dictionary here!
            length
        )

        # Prevent duplicating the start character if the model already prepends it
        if isinstance(generated_string, str):
             name = generated_string
        elif isinstance(generated_string, list):
             name = "".join(generated_string)
        else:
             name = str(generated_string)

    else:
        raise ValueError(f"Unknown model type: {type(model).__name__}")

    # Ensure the final string is nicely formatted (removing newlines for cleaner printing)
    return name[:length].replace('\n', ' ')

# --- Try running it again! ---
print("RNN:", generate_name(rnn_model, 'a', c_to_idx, idx_to_char, vocab_size))
print("BiLSTM:", generate_name(blstm_model, 'a', c_to_idx, idx_to_char, vocab_size))
print("Attention:", generate_name(attn_model, 'a', c_to_idx, idx_to_char, vocab_size))

def compute_metrics(generated_names, training_data):
    """
    Computes Novelty Rate and Diversity for a list of generated names.
    """
    if not generated_names:
        return 0.0, 0.0

    # Convert training data to a set for O(1) lookups
    training_set = set(training_data)
    total_generated = len(generated_names)

    # 1. Novelty Rate: (Generated names not in training set) / (Total generated names)
    novel_names = [name for name in generated_names if name not in training_set]
    novelty_rate = (len(novel_names) / total_generated) * 100

    # 2. Diversity: (Unique generated names) / (Total generated names)
    unique_generated = set(generated_names)
    diversity = len(unique_generated) / total_generated

    return novelty_rate, diversity

# ==========================================
# Example Usage & Comparison Setup
# ==========================================

# 1. Provide your training data
training_data = data

# 2. Define the characters your model knows (assuming lowercase English letters)
# If you have a specific list of characters in your vocab, use that instead!
valid_start_chars = list(string.ascii_lowercase)

# 3. Generate the outputs using your custom function
# We are generating 100 names per model here. Adjust the range(100) if you want more/less.
model_outputs = {
    "Vanilla RNN": [
        generate_name(rnn_model, random.choice(valid_start_chars), c_to_idx, idx_to_char, vocab_size)
        for _ in range(100)
    ],

    "BiLSTM": [
        generate_name(blstm_model, random.choice(valid_start_chars), c_to_idx, idx_to_char, vocab_size)
        for _ in range(100)
    ],

    "Attention": [
        generate_name(attn_model, random.choice(valid_start_chars), c_to_idx, idx_to_char, vocab_size)
        for _ in range(100)
    ]
}

# 4. Compute and Compare
print(f"{'Model':<15} | {'Novelty Rate (%)':<18} | {'Diversity Ratio':<15}")
print("-" * 55)

for model_name, generated_names in model_outputs.items():
    novelty, diversity = compute_metrics(generated_names, training_data)
    print(f"{model_name:<15} | {novelty:<18.2f} | {diversity:<15.4f}")

print("RNN:", generate_name(rnn_model, 'd', c_to_idx, idx_to_char, vocab_size))
print("BiLSTM:", generate_name(blstm_model, 'd', c_to_idx, idx_to_char, vocab_size))
print("Attention:", generate_name(attn_model, 'd', c_to_idx, idx_to_char, vocab_size))

print("RNN:", generate_name(rnn_model, 'i', c_to_idx, idx_to_char, vocab_size))
print("BiLSTM:", generate_name(blstm_model, 'i', c_to_idx, idx_to_char, vocab_size))
print("Attention:", generate_name(attn_model, 'i', c_to_idx, idx_to_char, vocab_size))



print("RNN:", generate_name(rnn_model, 'e', c_to_idx, idx_to_char, vocab_size))
print("BiLSTM:", generate_name(blstm_model, 'e', c_to_idx, idx_to_char, vocab_size))
print("Attention:", generate_name(attn_model, 'e', c_to_idx, idx_to_char, vocab_size))

print("RNN:", generate_name(rnn_model, 'm', c_to_idx, idx_to_char, vocab_size))
print("BiLSTM:", generate_name(blstm_model, 'm', c_to_idx, idx_to_char, vocab_size))
print("Attention:", generate_name(attn_model, 'm', c_to_idx, idx_to_char, vocab_size))

print("RNN:", generate_name(rnn_model, 'r', c_to_idx, idx_to_char, vocab_size,length=5))
print("BiLSTM:", generate_name(blstm_model, 'r', c_to_idx, idx_to_char, vocab_size,length=5))
print("Attention:", generate_name(attn_model, 'r', c_to_idx, idx_to_char, vocab_size,length=5))

import random
import string

filename = "generated_names.txt"
num_names = 100

# Get all lowercase letters to choose from
valid_chars = string.ascii_lowercase

with open(filename, "w") as f:
    # Generate RNN Names
    f.write("--- RNN Model ---\n")
    for _ in range(num_names):
        start_char = random.choice(valid_chars)
        name = generate_name(rnn_model, start_char, c_to_idx, idx_to_char, vocab_size)
        f.write(name + "\n")

    # Generate BiLSTM Names
    f.write("\n--- BiLSTM Model ---\n")
    for _ in range(num_names):
        start_char = random.choice(valid_chars)
        name = generate_name(blstm_model, start_char, c_to_idx, idx_to_char, vocab_size)
        f.write(name + "\n")

    # Generate Attention Names
    f.write("\n--- Attention Model ---\n")
    for _ in range(num_names):
        start_char = random.choice(valid_chars)
        name = generate_name(attn_model, start_char, c_to_idx, idx_to_char, vocab_size)
        f.write(name + "\n")

print(f"Successfully wrote 300 names to {filename}")

