# -*- coding: utf-8 -*-
"""NLU assignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJJ9gCCuuAneDlfJq6vspKuVifnl9clz
"""

!pip install pdfplumber
import pdfplumber
import os

from collections import Counter
import re

# i have used python lib. for structured extraction of data from pdf files
def text_extract(path):
    text = ""
    try:
        with pdfplumber.open(path) as pdf:
            for page in pdf.pages:
                text += page.extract_text() + "\n"
        return text
    except Exception as e:
        print(f"Error processing {path}: {e}")
        return ""

fo_path = "/content/"
corpus = [] # will collect data from each document

for file in os.listdir(fo_path):
    if file.endswith(".pdf"):
        full_path = os.path.join(fo_path, file)
        extracted_text = text_extract(full_path)
        if extracted_text:
            corpus.append(extracted_text)

# next we will remove the boilerplate text

def remove_repeatlines(text): # this will remove the repeated lines from text
    lines = text.split("\n")
    line_count = Counter(lines)

    cleaned_lines = [
        line for line in lines
        if line_count[line] < 3   # threshold can be changed ir required
    ]

    return "\n".join(cleaned_lines)

def remove_pn(text): # removes the page numbers using regular expression
    text = re.sub(r'\bPage\s*\d+\b', '', text)
    text = re.sub(r'^\d+\s*$', '', text, flags=re.MULTILINE)
    return text

def remove_metadata(text): # removes the other unnecessary data(url,isbn,etc)
    text = re.sub(r'doi:\s*\S+', '', text, flags=re.I)
    text = re.sub(r'ISBN\s*\S+', '', text, flags=re.I)
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'©\s*\d{4}', '', text)
    return text

def cleaned_text(text): # call all the cleaning functions
    text = remove_repeatlines(text)
    text = remove_pn(text)
    text = remove_metadata(text)
    return text
clean_corpus = [cleaned_text(doc) for doc in corpus]
# clean corpus have all the document data cleaned



"""**Lowercasing**"""

clean_corpus = [doc.lower() for doc in clean_corpus]

"""**Word Tokenisation**"""

import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Get the list of English stop words
stop_words = set(stopwords.words('english'))

# Create a more aggressive filter
tokenized_corpus = [
    [
        word for word in word_tokenize(doc)
        # Strip whitespace and punctuation before checking
        if word.strip(string.punctuation + " ").lower() not in stop_words
        # Optional: uncomment the line below to also remove pure punctuation tokens like "," or "."
        # and word.strip(string.punctuation + " ") != ""
    ]
    for doc in clean_corpus
]

"""**Removal of Excessive Punctuation and Non-Textual Content**"""

def remove_punc(text):
    text = re.sub(r'[^\w\s\.\,\?\!]', ' ', text)   # keep basic punctuation
    text = re.sub(r'[\.\,\?\!]{2,}', '.', text)    # remove repeated punctuation
    return text
def remove_non_ascii(text):
    return text.encode("ascii", "ignore").decode()
def remove_symbol(text):
    text = re.sub(r'\b[_\-]{2,}\b', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def clean_noise(text):
    text = remove_non_ascii(text)
    text = remove_punc(text)
    text = remove_symbol(text)
    return text
Final_clean_corpus = [clean_noise(doc) for doc in clean_corpus]

"""**Final Stats Afer Preprocessing**"""

import matplotlib.pyplot as plt
from wordcloud import WordCloud

net_corpus = [doc.split() for doc in Final_clean_corpus]
all_tokens = [token for doc in net_corpus for token in doc]

filtered_all_tokens = [token for token in all_tokens if token not in stop_words]
vocab = set(filtered_all_tokens)
# printing vocab statistics
print("=" * 40)
print("       DATASET STATISTICS")
print("=" * 40)
print(f"  Total doc.  : {len(Final_clean_corpus):,}")
print(f"  Total Tokens     : {len(filtered_all_tokens):,}")
print(f"  Vocab Size  : {len(vocab):,}")
print(f"  Avg Tokens/Doc   : {len(filtered_all_tokens) / len(Final_clean_corpus):,.1f}")
print("=" * 40)

word_freq = Counter(filtered_all_tokens)

wordcloud = WordCloud(
    width         = 1000,
    height        = 500,
    background_color = "white",
    colormap      = "viridis",
    max_words     = 150,
    collocations  = False        # avoids duplicate bigrams
).generate_from_frequencies(word_freq)

plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud – Most Frequent Words (Stopwords Removed)", fontsize=18, fontweight="bold", pad=15)
plt.tight_layout()
plt.show()

#printing top 20 most freq qords
print("\nTop 20 most freq. words (Stopwords Removed):")
print("-" * 30)
for word, freq in word_freq.most_common(20):
    print(f"  {word:<20} {freq:>6,}")



"""**Model**"""

import numpy as np
from collections import Counter

# Flatten tokens
tokens = [word for doc in net_corpus for word in doc]

# Build vocabulary
vocab = list(set(tokens))
word_to_idx = {w:i for i,w in enumerate(vocab)}
idx_to_word = {i:w for w,i in word_to_idx.items()}

V = len(vocab)   # vocab size

"""**Trainning CBOW model**"""

window_size = 2

training_data = []

for sentence in net_corpus:
    sentence_idx = [word_to_idx[w] for w in sentence]

    for i in range(window_size, len(sentence_idx) - window_size):

        context = []
        for j in range(-window_size, window_size + 1):
            if j != 0:
                context.append(sentence_idx[i+j])

        target = sentence_idx[i]

        training_data.append((context, target))

N = 120   # embedding dimension

W1_cbow = np.random.randn(V, N) * 0.01
W2_cbow = np.random.randn(N, V) * 0.01

def softmax(x):
    e = np.exp(x - np.max(x))
    return e / np.sum(e)

lr = 0.049
epochs = 20

for epoch in range(epochs):

    loss = 0

    for context, target in training_data:

        # ----- Forward pass -----

        # average context embeddings
        h = np.mean(W1_cbow[context], axis=0)   # hidden layer

        u = np.dot(h, W2_cbow)                  # output
        y_pred = softmax(u)

        eps = 1e-10
        loss -= np.log(y_pred[target] + eps)

        # ----- Backprop -----

        y_true = np.zeros(V)
        y_true[target] = 1

        e = y_pred - y_true

        dW2 = np.outer(h, e)
        dh = np.dot(W2_cbow, e)

        # distribute gradient to context words
        for word in context:
            W1_cbow[word] -= lr * dh / len(context)

        W2_cbow -= lr * dW2

    print("Epoch:", epoch, "Loss:", loss)
    print("Epoch:", epoch, "Avg Loss:", loss/len(training_data))

target_word = "mtech"

if target_word in word_to_idx:
    # 1. Get the integer index for the word
    word_idx = word_to_idx[target_word]

    # 2. Fetch the 300-dimensional vector from your trained weight matrix
    vector = W1_cbow[word_idx]

    # 3. Convert the NumPy array of floats into a comma-separated string
    vector_csv = ", ".join(map(str, vector))

    print(f"--- 300-D Vector for '{target_word}' ---")
    print(vector_csv)
else:
    print(f"Oops! '{target_word}' is not in the vocabulary.")
    print("Tip: Check if your corpus was perfectly lowercased, or try 'Jodhpur' instead.")

file_name = 'filtered_tokens.txt'

# 2. Open the file in write mode ('w') and save the tokens
with open(file_name, 'w', encoding='utf-8') as f:
    # Join the list into a single string, separated by newlines, and write it
    f.write('\n'.join(filtered_all_tokens))

print(f"Success! Tokens saved to {file_name}")

"""**Cosine Similarity**"""

word_embeddings_cbow = W1_cbow

from sklearn.metrics.pairwise import cosine_similarity

def near_words_cbow(word, topk=5):

    idx = word_to_idx[word]
    vec = word_embeddings_cbow[idx].reshape(1,-1)

    sims = cosine_similarity(vec, word_embeddings_cbow)[0]

    best = sims.argsort()[-topk-1:][::-1]

    return [idx_to_word[i] for i in best if i != idx][:topk]

print(word_embeddings_cbow.shape)

"""**Training Skip-gram with neg sampling**"""

window_size = 2

training_pairs = []

for sentence in net_corpus:
    sentence_idx = [word_to_idx[w] for w in sentence]

    for i, center in enumerate(sentence_idx):

        start = max(0, i-window_size)
        end = min(len(sentence_idx), i+window_size+1)

        for j in range(start, end):
            if i != j:
                context = sentence_idx[j]
                training_pairs.append((center, context))

embedding_dim = 120

W1_sg = np.random.randn(V, embedding_dim) * 0.01
W2_sg = np.random.randn(embedding_dim, V) * 0.01

"""**Negative sampling applied**"""

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

lr = 0.049
epochs = 20
K = 5   # number of negative samples

for epoch in range(epochs):

    loss = 0

    for center, context in training_pairs:

        # center word embedding
        h = W1_sg[center]

        # -------- Positive sample --------
        score_pos = np.dot(h, W2_sg[:, context])
        pred_pos = sigmoid(score_pos)

        loss -= np.log(pred_pos + 1e-10)

        grad_pos = pred_pos - 1

        dh = grad_pos * W2_sg[:, context]
        W2_sg[:, context] -= lr * grad_pos * h

        # -------- Negative samples --------
        neg_samples = np.random.choice(V, K)

        for neg in neg_samples:

            score_neg = np.dot(h, W2_sg[:, neg])
            pred_neg = sigmoid(score_neg)

            loss -= np.log(1 - pred_neg + 1e-10)

            grad_neg = pred_neg

            dh += grad_neg * W2_sg[:, neg]
            W2_sg[:, neg] -= lr * grad_neg * h

        # update center embedding
        W1_sg[center] -= lr * dh

    print("Epoch:", epoch, "Loss:", loss)
    print("Epoch:", epoch, "Avg Loss:", loss/len(training_pairs))

"""**Cosine Similarity**"""

word_embeddings_sg = W1_sg

from sklearn.metrics.pairwise import cosine_similarity

def near_words_sg(word, topk=5):

    idx = word_to_idx[word]
    vec = word_embeddings_sg[idx].reshape(1,-1)

    sims = cosine_similarity(vec, word_embeddings_sg)[0]

    best = sims.argsort()[-topk-1:][::-1]

    return [idx_to_word[i] for i in best if i != idx][:topk]



"""**SEMANTIC ANALYSIS**



"""



print(near_words_sg("research"))
print(near_words_sg("student"))
print(near_words_sg("phd"))
print(near_words_sg("examination"))
print(near_words_sg("marks"))

print(near_words_cbow("research"))
print(near_words_cbow("student"))
print(near_words_cbow("phd"))
print(near_words_cbow("examination"))
print(near_words_cbow("marks"))

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def analogy_cbow(a, b, c, topk=3):
    # similar to  b - a + c
    vec = word_embeddings_cbow[word_to_idx[b]] - word_embeddings_cbow[word_to_idx[a]] + word_embeddings_cbow[word_to_idx[c]]

    sims = cosine_similarity(vec.reshape(1,-1), word_embeddings_cbow)[0]

    best = sims.argsort()[-topk-3:][::-1]

    results = []
    for i in best:
        word = idx_to_word[i]
        if word not in [a, b, c]:
            results.append((word, sims[i]))
        if len(results) == topk:
            break

    return results

print("CBOW analogy:")
print("UG : BTech :: PG : ?")
print(analogy_cbow("ug", "btech", "pg"))

def analogy_sg(a, b, c, topk=3):

    vec = word_embeddings_sg[word_to_idx[b]] - word_embeddings_sg[word_to_idx[a]] + word_embeddings_sg[word_to_idx[c]]

    sims = cosine_similarity(vec.reshape(1,-1), word_embeddings_sg)[0]

    best = sims.argsort()[-topk-3:][::-1]

    results = []
    for i in best:
        word = idx_to_word[i]
        if word not in [a, b, c]:
            results.append((word, sims[i]))
        if len(results) == topk:
            break

    return results

print("Skip-gram analogy:")
print("UG : btech :: PG : ?")
print(analogy_sg("ug", "btech", "pg"))

print(analogy_cbow("student", "marks", "faculty"))
print(analogy_sg("student", "marks", "faculty"))

print(analogy_cbow("btech", "project", "phd"))
print(analogy_sg("btech", "project", "phd"))

print(analogy_cbow("students", "hostels", "faculty"))
print(analogy_sg("students", "hostels", "faculty"))

print(analogy_cbow("male", "pass", "female"))
print(analogy_sg("male", "pass", "female"))

"""**Visualisation**"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

selected_words = [
    "student", "teacher", "professor", "researcher", "phd",
    "ug", "pg", "btech", "mtech",
    "exam", "quiz", "marks", "result", "grade"
]

def get_word_vectors(embeddings, words):
    valid_words = [w for w in words if w in word_to_idx]
    vectors = np.array([embeddings[word_to_idx[w]] for w in valid_words])
    return valid_words, vectors

def plot_pca(embeddings, words, title):

    labels, vectors = get_word_vectors(embeddings, words)

    pca = PCA(n_components=2)
    reduced = pca.fit_transform(vectors)

    plt.figure(figsize=(6,6))
    plt.scatter(reduced[:,0], reduced[:,1])

    for i, word in enumerate(labels):
        plt.annotate(word, (reduced[i,0], reduced[i,1]))

    plt.title(title)
    plt.xlabel("PC1")
    plt.ylabel("PC2")
    plt.show()

def plot_tsne(embeddings, words, title):

    labels, vectors = get_word_vectors(embeddings, words)

    tsne = TSNE(n_components=2, random_state=42, perplexity=5)
    reduced = tsne.fit_transform(vectors)

    plt.figure(figsize=(6,6))
    plt.scatter(reduced[:,0], reduced[:,1])

    for i, word in enumerate(labels):
        plt.annotate(word, (reduced[i,0], reduced[i,1]))

    plt.title(title)
    plt.xlabel("Dim 1")
    plt.ylabel("Dim 2")
    plt.show()

# CBOW
plot_pca(word_embeddings_cbow, selected_words, "CBOW - PCA")
plot_tsne(word_embeddings_cbow, selected_words, "CBOW - t-SNE")

# Skip-gram
plot_pca(word_embeddings_sg, selected_words, "Skip-gram - PCA")
plot_tsne(word_embeddings_sg, selected_words, "Skip-gram - t-SNE")

